-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Categories"
(
    "categoryID" integer NOT NULL,
    "categoryName" text NOT NULL,
    description text,
    PRIMARY KEY ("categoryID")
);

CREATE TABLE IF NOT EXISTS public.customers
(
    "customerID" text NOT NULL,
    "companyName" text NOT NULL,
    "contactName" text,
    "contactTitle" text,
    city text,
    country text NOT NULL,
    PRIMARY KEY ("customerID")
);

CREATE TABLE IF NOT EXISTS public.employees
(
    "employeeID" integer,
    "employeeName" text NOT NULL,
    title text,
    city text,
    country text NOT NULL,
    "reportsTo" integer,
    PRIMARY KEY ("employeeID")
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    "orderID" integer,
    "productID" integer,
    "unitPrice" numeric,
    quantity integer,
    discount numeric,
    PRIMARY KEY ("orderID", "productID")
);

CREATE TABLE IF NOT EXISTS public.orders
(
    "orderID" integer,
    "customerID" text NOT NULL,
    "employeeID" integer NOT NULL,
    "orderDate" date NOT NULL,
    "requiredDate" date,
    "shippedDate" date,
    "shipperID" integer,
    freight numeric,
    PRIMARY KEY ("orderID")
);

CREATE TABLE IF NOT EXISTS public.products
(
    "productID" integer NOT NULL,
    "productName" text,
    "quantityPerUnit" text,
    "unitPrice" numeric,
    discontinued integer,
    "categoryID" integer,
    PRIMARY KEY ("productID"),
    CONSTRAINT "Unique ProductID" UNIQUE ("productID")
);

CREATE TABLE IF NOT EXISTS public.shippers
(
    "shipperID" integer,
    "companyName" text,
    PRIMARY KEY ("shipperID")
);

ALTER TABLE IF EXISTS public."Categories"
    ADD FOREIGN KEY ("categoryID")
    REFERENCES public.products ("categoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customers
    ADD FOREIGN KEY ("customerID")
    REFERENCES public.orders ("customerID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY ("employeeID")
    REFERENCES public.orders ("employeeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY ("orderID")
    REFERENCES public.order_details ("orderID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY ("productID")
    REFERENCES public.order_details ("productID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.shippers
    ADD FOREIGN KEY ("shipperID")
    REFERENCES public.orders ("shipperID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;