---- Q1 ------------
SELECT 	EXTRACT(YEAR FROM ORDER_DATE) AS ORDER_YEAR,	EXTRACT(QUARTER FROM ORDER_DATE) AS QUARTER,	COUNT(*) AS ORDERCOUNT,	AVG(FREIGHT) AS FREIGHT
FROM ORDERS WHERE FREIGHT > 100 GROUP BY EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(QUARTER FROM ORDER_DATE) ORDER BY	ORDER_YEAR, QUARTER;

---Q2----------------
SELECT SHIP_REGION,	COUNT(ORDER_ID) AS ORDER_COUNT,MIN(FREIGHT) AS MIN_FREIGHT,MAX(FREIGHT) AS MAX_FREIGHT FROM ORDERS GROUP BY SHIP_REGION
HAVING COUNT(ORDER_ID) >= 5  AND SHIP_REGION IS NOT NULL ORDER BY ORDER_COUNT DESC LIMIT 10;

-----Q3--------------
SELECT TITLE AS DESIGNATION FROM EMPLOYEES UNION SELECT CONTACT_TITLE AS DESIGNATION FROM CUSTOMERS;
SELECT TITLE AS DESIGNATION FROM EMPLOYEES UNION ALL SELECT CONTACT_TITLE AS DESIGNATION FROM CUSTOMERS;

---Q4-----------
SELECT category_id FROM products WHERE units_in_stock > 0 INTERSECT SELECT category_id FROM products WHERE discontinued = 1 ORDER BY category_id

---Q5-----------
SELECT order_id FROM order_details EXCEPT SELECT order_id FROM order_details WHERE discount != 0 ORDER BY order_id;
